export const mockProjects = [
  {
    id: "p1",
    title: "LangClips",
    techs: [
      "Next.js",
      "NestJS",
      "Redis",
      "Whisper AI",
      "FFmpeg",
      "IndexedDB",
      "Cloudflare R2",
    ],
    imageUrl: "/projects/langclips/hero.png",
    link: "https://github.com/victor-lis-bronzo/langclips",
  },
  {
    id: "p2",
    title: "Portfólio & Assistente IA",
    techs: [
      "Next.js",
      "TypeScript",
      "Google Gemini SDK",
      "Canvas API",
      "Firebase",
      "Turborepo",
    ],
    imageUrl: "/projects/portfolio-ia/hero.png",
    link: "https://portfolio.victorlisbronzo.me",
  },
  {
    id: "p3",
    title: "Git Assets",
    techs: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Node.js",
      "Fastify",
      "Prisma ORM",
      "PostgreSQL",
    ],
    imageUrl: "/projects/gitassets/hero.png",
    link: "https://github.com/victor-lis-bronzo/gitassets",
  },
  {
    id: "p4",
    title: "Harddex",
    techs: ["Next.js", "Drizzle ORM", "PostgreSQL", "TailwindCSS"],
    imageUrl: "/projects/harddex/hero.png",
    link: "https://github.com/victor-lis-bronzo/harddex-landing",
  },
  {
    id: "p5",
    title: "Mercado Pago API",
    techs: ["Node.js", "Fastify", "TypeScript", "Webhooks"],
    imageUrl: "/projects/mercado-pago/hero.png",
    link: "https://github.com/victor-lis-bronzo/mercado-pago-api",
  },
  {
    id: "p6",
    title: "VPS Config",
    techs: ["Docker", "NGINX", "MQTT", "N8N", "Portainer"],
    imageUrl: "/projects/vps-config/readme.png",
    link: "https://github.com/victor-lis-bronzo/vps-config",
  },
  {
    id: "p7",
    title: "Portfólio 3D",
    techs: ["Three-js", "Cannon-ES", "Parcel", "Dat.Gui", "TypeScript"],
    imageUrl: "/projects/portfolio-3d/banner.png",
    link: "https://victorlisbronzo.me",
  },
];
